### ISSUE TITLE
Bug after upgrade library to new version

### ISSUE THREAD

**Issue by ZaydelEduard** [anderscheow/Validator#2]
What is wrong?

Add rule in activity:
http://joxi.ru/gmv0zKPUxpDy5A

Custom rule class:
http://joxi.ru/xAen6V9HYWKpBr

**Comment by ZaydelEduard** [comment]
Changed parameter in generic to Any instead of String and everything works fine.

**Comment by anderscheow** [comment]
I just realize there's limitation on it. I can't include different generic into same ArrayList. So the only way to fix it is to remove generic type on BaseRule and validate() will accept only "Any?" as parameter. You need to do your own validation under validate() with Any parameter.

I will release a new version which remove generic type from BaseRule
