### ISSUE TITLE
NotEqualTo Base Rule not Working Correctly

### ISSUE THREAD

**Issue by LaserStony** [anderscheow/Validator#3]
The `NotEqualRule`and `EqualRule ` are not working for dynamic texts. For Example

```
Validation passwordConfirmValidation = new Validation(confirmPasswordWrapper).add(new NotEqualRule(password.getText(),"Passwords Are not equal"));
```

This Doesn't Work. and If you remove the Custom error, It says: The value is not equal to '' as error text

**Comment by anderscheow** [comment]
Currently does not support dynamic text. You need to recreate validation object in order to have newer reference of your text

**Comment by LaserStony** [comment]
Hmmmm... So something like this: 
`Validation passwordConfirmValidation = new Validation(confirmPasswordWrapper).add(new NotEqualRule(passwordValidation));`
?

**Comment by anderscheow** [comment]
Yea, similar way.
You can refer to [this](https://github.com/anderscheow/Validator/blob/master/sample/src/main/java/io/github/anderscheow/validator/sample/MainActivity.kt)

**Comment by LaserStony** [comment]
Your embedded link to the Sample Activity doesn't show the implementation for NotEquaRlule.

**Comment by anderscheow** [comment]
The main problem is the custom error text is not working?

**Comment by LaserStony** [comment]
yes. When I pass the InputLayout, It prints sets error to: (com.something.something......) and If I pass text It sets Error Text to : Value not equal to ''
with nothing between the commas...

**Comment by anderscheow** [comment]
Can you show me the sample screens correspond to your code?

**Comment by LaserStony** [comment]
@anderscheow I removed the Implementation and had to do the Not Equal Verification manually... hmmm.. I'll make a new project and send you the Screens and code in a bit...

**Comment by anderscheow** [comment]
Sure, in the mean time I'll test on my side

**Comment by anderscheow** [comment]
Is your "confirmPasswordWrapper" TextInputLayout?

**Comment by LaserStony** [comment]
Yes it is...
