### ISSUE TITLE
Hi , About the Validator.kt

### ISSUE THREAD

**Issue by phoebewow** [anderscheow/Validator#4]
Line 51 code:
val value = (editText?.text ?: validation.textInput).toString()
It should be changed to,
val value = (editText?.text ?: validation.textInput?.text).toString()

**Comment by anderscheow** [comment]
`validation.textInput` is `Any` type

**Comment by phoebewow** [comment]
So, I need use this?
val et:TextInputEditText
Validation(et?.text)

**Comment by anderscheow** [comment]
There are two ways:
Method 1:
```
val et:TextInputEditText...
Validation(et?.text?.toString() ?: "")   <- As Validation(...) only accept non-nullable value
```
or
Method 2 (**Recommended**):
```
val inputLayout: TextInputLayout...
Validation(inputLayout)   <- Using this will handle everything in Method 1
```

**Comment by phoebewow** [comment]
OK, I see. THANKS!

**Comment by anderscheow** [comment]
No problem. Glad that I'm able to help you.
