### ISSUE TITLE
is this Library this only useful on android?

### ISSUE THREAD

**Issue by mustii82** [anderscheow/Validator#6]
is this Library this only useful on android?

I worked on a similar project and just want to know if I can stop my work if this is compatible with Kotlin JVM :D

**Comment by anderscheow** [comment]
This will only works on Android. Because it required TextInputLayout which is Material Design library.

**Comment by mustii82** [comment]
what about an abstraction layer? would be nice to use this on Kotlin JVM and other Targets

**Comment by anderscheow** [comment]
Currently go no plan on it, but it's nice if you can submit PR on it. 😁
