### ISSUE TITLE
Password confirmation validation rule proposal

### ISSUE THREAD

**Issue by Kaned1as** [anderscheow/Validator#7]
This is a suggestion to add PasswordMatchRule for "confirm password" behaviours, along with `withPasswordConfirmation(...)` extensions.

Code follows:

```kotlin
class PasswordMatchRule(private val passwordInput: EditText, errorRes: Int) : BaseRule(errorRes) {

    override fun validate(value: String?): Boolean {
        return passwordInput.text.toString() == value
    }

}
```

**Comment by anderscheow** [comment]
Previously I'm having a thought of adding this, but it's almost similar to EqualRule

**Comment by Kaned1as** [comment]
The choice is between being intuitive and not overly bloated by default. Maybe the proper solution is to add `BaseRule` constructor accepting arbitrary lambda.
